//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnerDash.Learner.Quiz
{
    public partial class History
    {
        /// <summary>
        /// rptAttempts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAttempts;

        /// <summary>
        /// lblNoAttempts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoAttempts;
    }
}