//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aidify_assigment.Admin
{
    public partial class Roles
    {
    }
}
