//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnerDash.Learner
{
    public partial class Badges
    {
        /// <summary>
        /// lblNoBadges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoBadges;

        /// <summary>
        /// rptBadges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBadges;
    }
}