//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnerDash.Learner
{
    public partial class Certificates
    {
        /// <summary>
        /// lblNoCerts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoCerts;

        /// <summary>
        /// rptCertificates control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCertificates;
    }
}