//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnerDash.Learner
{
    public partial class Challenges
    {
        /// <summary>
        /// lblNoChallenges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoChallenges;

        /// <summary>
        /// rptChallenges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChallenges;
    }
}