//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aidify_assigment.Learner
{
    public partial class Discussions
    {
        protected global::System.Web.UI.WebControls.Label lblDiscussionStatus;

        protected global::System.Web.UI.WebControls.DropDownList ddlModule;

        protected global::System.Web.UI.WebControls.TextBox txtThreadTitle;

        protected global::System.Web.UI.WebControls.TextBox txtThreadBody;

        protected global::System.Web.UI.WebControls.Button btnCreateThread;

        protected global::System.Web.UI.WebControls.DropDownList ddlModuleFilter;

        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        protected global::System.Web.UI.WebControls.Label lblNoThreads;

        protected global::System.Web.UI.WebControls.Repeater rptThreads;
    }
}
