//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnerDash.Learner
{
    public partial class Events
    {
        /// <summary>
        /// lblNoEvents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoEvents;

        /// <summary>
        /// rptEvents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEvents;
    }
}